apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
      version: v4
  template:
    metadata:
      labels:
        app: node-app
        version: v4
    spec:
      containers:
        - name: node-app
          image: k8s-node-app:v4
          imagePullPolicy: Never
          ports:
            - containerPort: 3000