apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
      version: stable
  template:
    metadata:
      labels:
        app: node-app
        version: stable
    spec:
      containers:
      - name: node-app
        image: k8s-node-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000