name: Deploy with Selected Strategy

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'Deployment Strategy'
        required: true
        default: 'recreate'
        type: choice
        options:
          - recreate
          - rolling
          - canary
          - bluegreen

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy with selected strategy
        run: |
          echo "Strategy selected: ${{ github.event.inputs.strategy }}"
          STRATEGY="${{ github.event.inputs.strategy }}"

          if [ "$STRATEGY" = "recreate" ]; then
            kubectl apply -f deployment-recreate.yaml
          
          elif [ "$STRATEGY" = "rolling" ]; then
            kubectl apply -f deployment-RollingUpdate.yaml
          
          elif [ "$STRATEGY" = "canary" ]; then
            kubectl apply -f deployment-canary.yaml
          
          elif [ "$STRATEGY" = "bluegreen" ]; then
            kubectl apply -f deployment-blue.yaml
            kubectl apply -f service.yaml
          else
            echo "Invalid strategy selected."
            exit 1
          fi