name: Local CI/CD with Self-Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t k8s-node-app:v1 .

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Show Pods and Services
        run: |
          kubectl get pods
          kubectl get svc