name: Deploy with Selected Strategy

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'Deployment Strategy (recreate / rolling / canary / bluegreen)'
        required: true
        default: 'recreate'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Start Minikube
      run: |
        minikube start || echo "Minikube already running"

    - name: Deploy Based on Strategy
      run: |
        STRATEGY="${{ github.event.inputs.strategy }}"

        if [ "$STRATEGY" = "recreate" ]; then
          kubectl apply -f k8s/recreate-deployment.yaml

        elif [ "$STRATEGY" = "rolling" ]; then
          kubectl apply -f k8s/rollingupdate-deployment.yaml

        elif [ "$STRATEGY" = "canary" ]; then
          kubectl apply -f k8s/canary-deployment.yaml

        elif [ "$STRATEGY" = "bluegreen" ]; then
          kubectl apply -f k8s/blue-deployment.yaml
          echo "Waiting for Blue deployment to stabilize..."
          sleep 10
          echo "Now switching service to Green..."
          kubectl apply -f k8s/green-deployment.yaml
          kubectl apply -f k8s/green-service.yaml

        else
          echo "Invalid strategy: $STRATEGY"
          exit 1
        fi